name: Pipeline Orchestrator

on:
  pull_request:
    branches: [main]

jobs:
  pipeline-scan:
    uses: ./.github/workflows/pipeline-scan.yml
    secrets: inherit
    permissions:
      security-events: write
      contents: read # only needed for private repos
      actions: read # only needed for private repos

  code-scan:
    needs: pipeline-scan
    uses: ./.github/workflows/code-scan.yml

  secrets-scan:
    needs: pipeline-scan
    uses: ./.github/workflows/secrets-scan.yml

  iac-scan:
    needs: pipeline-scan
    uses: ./.github/workflows/iac-scan.yml

  build-and-container-scan:
    needs: [code-scan, secrets-scan]
    permissions:
      contents: read
      security-events: write
      actions: read
    uses: ./.github/workflows/build-and-container-scan.yml

  deploy-infrastructure:
    needs: iac-scan
    uses: ./.github/workflows/deploy-infrastructure.yml

  deploy-application:
    needs: [build-and-container-scan, deploy-infrastructure]
    uses: ./.github/workflows/deploy-application.yml

  runtime-infra-scan:
    needs: deploy-application
    uses: ./.github/workflows/runtime-infra-scan.yml
    with:
      environment: ${{ github.ref_name }}
      app-url: https://workshop-app-${{ github.ref_name }}.example.com
    permissions:
      id-token: write
    secrets:
      AWS_IAM_ROLE_ARN: ${{ secrets.AWS_IAM_ROLE_ARN }}

  dast:
    needs: deploy-application
    uses: ./.github/workflows/dast.yml
    with:
      environment: ${{ github.ref_name }}
      app-url: https://workshop-app-${{ github.ref_name }}.example.com

  integration-test:
    needs: deploy-application
    uses: ./.github/workflows/integration-test.yml
    with:
      environment: ${{ github.ref_name }}
      app-url: https://workshop-app-${{ github.ref_name }}.example.com

